### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by stebunovd** [mantoni/consolify#5]
Files produced by consolify are not compatible with IE8. I have discovered 2 problems which cause this, but probably there could be more.

1. ansi_up creates objects with properties named *class*, but *class* is a reserved word in IE8 and throws an error. Pull request - https://github.com/drudru/ansi_up/pull/11
2. convert-source-map (used by source-mapper) contains calls to \_\_defineGetter\_\_, but this method is supported by IE >= 11 only https://github.com/thlorenz/convert-source-map/blob/master/index.js#L131

**Comment by mantoni** [comment]
I couldn't care less about IE 8. Unfortunately, I have to support IE 9, but I will not put any effort into this, nor am I willing to "officially" support it.
Sorry.
